export const pricingPlans = [
  {
    name: "Free",
    price: "₩0",
    period: "무료",
    slotsText: "슬롯 5개 제한",
    description: "소규모 서버를 위한 기본적인 알림 서비스",
    icon: "zap" as const,
    color: "from-gray-500 to-slate-600",
    features: ["슬롯 5개", "실시간 알림", "기본 알림 전송"],
    badge: "처음 시작하는 분들에게 추천",
    buttonVariant: "outline" as const,
    isPopular: false,
    isRecommended: false,
  },
  {
    name: "₩3,000 단일 구매",
    price: "₩3,000",
    period: "1회 구매",
    slotsText: "슬롯 5개 추가 (총 10개)",
    description: "한 번의 결제로 장기 사용 가능한 플랜",
    icon: "star" as const,
    color: "from-blue-500 to-cyan-600",
    features: ["슬롯 10개", "실시간 알림", "기본 알림 전송"],
    badge: "가장 인기있는 선택",
    buttonVariant: "primary" as const,
    isPopular: true,
    isRecommended: false,
  },
  {
    name: "₩5,000 단일 구매",
    price: "₩5,000",
    period: "1회 구매",
    slotsText: "슬롯 10개 추가 (총 15개)",
    description: "추가 슬롯이 필요한 중간 규모 서버를 위한 플랜",
    icon: "shield" as const,
    color: "from-purple-500 to-pink-600",
    features: ["슬롯 15개", "실시간 알림", "기본 알림 전송"],
    badge: "추가 슬롯 필요 시 추천",
    buttonVariant: "outline" as const,
    isPopular: false,
    isRecommended: false,
  },
  {
    name: "월 ₩2,000 정기 구독",
    price: "월 ₩2,000",
    period: "정기 구독",
    slotsText: "슬롯 총 250개 + 추가 부가 기능",
    description: "대규모 서버를 위한 프리미엄 플랜 + 추가 기능",
    icon: "crown" as const,
    color: "from-primary to-emerald-500",
    features: [
      "슬롯 250개",
      "실시간 알림",
      "고급 필터링 기능",
      "커스텀 웹훅 기능 지원",
      "빠른 알림 전송 (우선순위)",
    ],
    badge: "다양한 부가 기능",
    buttonVariant: "primary" as const,
    isPopular: false,
    isRecommended: true,
  },
];
